# Generated by Django 5.0.4 on 2024-06-26 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='имя')),
                ('email', models.EmailField(max_length=254)),
                ('telegram_account', models.CharField(max_length=50)),
                ('coments', models.TextField(blank=True, verbose_name='Коментарий')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='вопрос')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('answer', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nastya.clients')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nastya.questions')),
            ],
        ),
    ]
